# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a05de859f060a423fc9d0d23b3bf32c26ef9b0d93e68e78c96d47a6343bf8c65ff9887bbb45b69609e254aafa4b8206513db1a548fd40f02405382e7a43acc0

test:
  secret_key_base: c8b098bba564cb88ec2cdf8d00ef03ca44c3579c72484dac6aaaf241b15d5810b5c7887ced4f49a2e03544d15d19c65c23c06dcff8b61cbe3ebfe5c328685b7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
